---
title: "Central Limit Theorem"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu  
    source_code: embed
runtime: shiny
---



# משפט הגבול המרכזי

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
pacman::p_load(data.table, tidyverse, colourpicker, ggeasy,
               shiny, flexdashboard, openxlsx, glue,
               stringi)

ch <- function(a){
  as.character(a)
}

render_ggplot_hist <- function(data, n, m, select_m, dist, bins_num, fill_str, title_type){
  if(title_type == 'dist'){
    title_str <- glue('sample {select_m} of tot {m} samples of {dist} dist length {n}')
  } else {
    title_str <- glue('dist of mean of tot {m} samples of {dist} dist length {n}')
  }
  
  data %>% 
    ggplot() +
    geom_histogram(aes_string(x = paste0("V", select_m), y = "..density.."),
                   fill = fill_str,
                   bins = bins_num) +
    geom_density(aes_string(x = paste0("V", select_m), y = '..density..'),
                 size = 3) +
    scale_y_continuous(expand = c(0,0)) +
    labs(
        title = title_str,
        subtitle = "",
        y = "",
        x = "",
        caption = "",
        color = "",
        fill = "",
        size = ""
        ) +
    theme_classic() +
      theme(axis.text.x = element_text(face="bold", size = 12, color = "black"),
        axis.text.y = element_text(size = 12, color = "black", face="bold"),
        axis.ticks = element_line(linetype = "blank"),
        legend.background = element_rect(fill = NA, colour = "black", linetype = "solid"),
        plot.subtitle = element_text(hjust = 1, size = 12), 
        plot.title = element_text(hjust = 0, size = 16, face="bold", color = "black"),
        panel.grid.major.y = element_line(size=1, colour = "#CFCFCF"),
        legend.position = "none",
        legend.title = element_blank()) +
    easy_remove_y_axis(what = 'line')
}

dist_hist_colr = '#71C0ED'
mean_hist_colr = '#194BA8'
```




Column {.sidebar}
-----------------------------------------------------------------------

```{r}

selectInput('dist',  label = 'מרחב הדגימה', c("norm", "uni", "exp", "poison", "binomial"),
                selected= 'norm')

selectInput("m", label = "מספר דגימות שמוגרלות:",
            seq(10, 4000, 5),
            selected= '500')


selectInput("n", label = "מספר התצפיות שמורגלות בכל דגימה",
            seq(10, 20000, 10),
            selected= '100')

renderUI({
selectInput("select_m", "מבט על דגימה תוצאות הגרלה מספר:", seq(1, as.integer(input$m), 1),
            selected= '1')
        })

sliderInput("mean", label = "בחר (אם רלוונטי) ממוצע",
            min = 0.1, max = 20,
            value = c(4))

sliderInput("sd", label = "בחר (אם רלוונטי) סטיית תקן",
            min = 0.1, max = 20,
            value = c(1))

sliderInput("lambda", label = "בחר (אם רלוונטי) למבדא",
            min = 5, max = 100,
            value = c(10))


renderUI({
  sliderInput("size", label = "בחר (אם רלוונטי) כמות לבינומאל",
            min = 1, max = , as.integer(input$n),
            value = c(10))
})

sliderInput("prob", label = "בחר (אם רלוונטי) סיכוי",
            min = 0.01, max = 1,
            value = c(0.5))


sliderInput("bins_num", label = "בחר כמה עמודות יהיו בהיסטוגרמה",
            min = 20, max = 200,
            value = c(30))


```

```{r}
norm_data <- 
  reactive({
matrix(rnorm( as.integer(input$n)* as.integer(input$m), mean = input$mean, sd = input$sd),  as.integer(input$n),       as.integer(input$m)) %>% as.data.frame()
  })

uni_data <- 
  reactive({
  as.data.table(matrix(runif(as.integer(input$n)* as.integer(input$m), min = 0, max = 1), as.integer(input$n),       as.integer(input$m)))
  })

exp_data <- 
  reactive({
  as.data.table(matrix(rexp(as.integer(input$n)* as.integer(input$m)), as.integer(input$n),       as.integer(input$m)))
  })

pois_data <- 
  reactive({
  as.data.table(matrix(rpois(as.integer(input$n)* as.integer(input$m), lambda = input$lambda), as.integer(input$n),       as.integer(input$m)))
  })

binomial_data <- 
  reactive({
  as.data.table(matrix(rbinom(as.integer(input$n)* as.integer(input$m), size = as.integer(input$size), prob = as.double(input$prob)), as.integer(input$n),       as.integer(input$m)))
  })


# data
data <- 
  reactive({
    if(input$dist == 'norm'){
      norm_data()
    } else if(input$dist == 'uni'){
      uni_data()
    } else if(input$dist == 'exp'){
      exp_data()
    }else if(input$dist == 'poison'){
      pois_data()
    } else {
      binomial_data()
    }
    
    
      })
```


Column
-----------------------------------------------------------------------

### התפלגות דגימה:

```{r}


renderPlot({
        render_ggplot_hist(data = data(), 
                           n = input$n,
                           m = input$m,
                           select_m = input$select_m,
                           dist = input$dist,
                           bins_num = input$bins_num,
                           fill_str = '#71C0ED',
                           title_type = "dist"
                           )
})
```


### התפלגות הממוצעים:
    
```{r}
renderPlot({
  as.data.table(x = map_dbl(data(), mean)) %>% 
        render_ggplot_hist(
                           n = input$n,
                           m = input$m,
                           select_m = '1',
                           dist = input$dist,
                           bins_num = input$bins_num,
                           fill_str = '#194BA8',
                           title_type = "mean"
                           )
})
```

# טבלת הנתונים

### כל עמודה מייצגת הגרלה של וקטור רנדומלי מתוך מרחב התפלגות

```{r}
renderTable({
  data()
  })

```

# טבלת ממוצעי ההגרלות

### וקטור הממוצעים

```{r}
renderTable({
  as.data.table(x = map_dbl(data(), mean))
})

```